# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0002_auto_20170912_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topic',
            new_name='question_title',
        ),
        migrations.AddField(
            model_name='question',
            name='question_poll',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
