# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0003_auto_20170918_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_poll',
        ),
    ]
