# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0004_remove_question_question_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qvotes',
            field=models.IntegerField(default=0),
        ),
    ]
