# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0005_auto_20170918_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cvotes',
        ),
        migrations.AlterField(
            model_name='answer',
            name='avotes',
            field=models.IntegerField(default=0),
        ),
    ]
