# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0006_auto_20170918_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
