# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0011_question_numans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='recentAnswer',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 21, 17, 56, 30, 651197, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
