# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutYourself',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
