# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0014_auto_20170922_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='regDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 22, 15, 14, 58, 566965, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
