# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0015_profile_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='static/images/demo/avatar.png', upload_to='static/images/demo/'),
        ),
    ]
