# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0017_auto_20170922_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numViews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='KMS/static/images/demo/avatar.png', upload_to='../static/images/demo/'),
        ),
    ]
