# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0018_auto_20170924_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='best',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='avatar.png', max_length=1000, upload_to=''),
        ),
    ]
