# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0019_auto_20171017_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
