# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0021_auto_20171017_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_solved',
            field=models.IntegerField(default=0),
        ),
    ]
