# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS', '0022_question_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bestAnswer',
            field=models.IntegerField(default=0),
        ),
    ]
